services:
  mongodb:
    image: mongo
    container_name: mongodb_chatapp
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aladmin
      - MONGO_INITDB_ROOT_PASSWORD=aladmin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aladmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aladmin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo: {}
