services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tdldb
      MYSQL_USER: aladmin
      MYSQL_PASSWORD: aladmin
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/data/mdb

volumes:
  mariadb: {}